table dim_news

	/// Distinct enriched news items.
	measure 'News Items' = DISTINCTCOUNT(dim_news[news_id])
		formatString: #,##0

	column news_id
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: news_id

	column language
		dataType: string
		summarizeBy: none
		sourceColumn: language

	column cefr_level
		dataType: string
		summarizeBy: none
		sourceColumn: cefr_level

	column domain
		dataType: string
		summarizeBy: none
		sourceColumn: domain

	column source_country
		dataType: string
		summarizeBy: none
		sourceColumn: source_country

	column title_translated
		dataType: string
		summarizeBy: none
		sourceColumn: title_translated

	column summary
		dataType: string
		summarizeBy: none
		sourceColumn: summary

	column english_gloss
		dataType: string
		summarizeBy: none
		sourceColumn: english_gloss

	column seen_date_key
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: seen_date_key

	partition dim_news = entity
		mode: directLake
		source
			entityName: dim_news
			schemaName: dbo
			expressionSource: DirectLake
